// Centralized icon exports from react-icons
import {
  FiMenu,
  FiX,
  FiHome,
  FiInfo,
  FiTool,
  FiBox,
  FiUsers,
  FiMail,
  FiChevronDown,
  FiScissors,
  FiPhone,
  FiMapPin,
  FiFacebook,
  FiTwitter,
  FiLinkedin,
  FiInstagram,
  FiActivity,
  FiPlusSquare,
  FiArrowRight,
  FiAward,
  FiClock,
  FiCheckCircle,
  FiShield,
  FiFileText,
  FiMessageCircle,
  FiTarget,
  FiEye,
  FiHeart,
  FiDownload,
  FiSend,
  FiSettings,
  FiCheck,
  FiMessageSquare,
  FiPenTool,
  FiHeadphones,
  FiArrowLeft,
} from 'react-icons/fi';

import { FaWhatsapp, FaStethoscope, FaUtensils } from 'react-icons/fa';
import { BiBed, BiBuilding } from 'react-icons/bi';

export {
  FiMenu as Menu,
  FiX as X,
  FiHome as Home,
  FiInfo as Info,
  FiTool as Tool,
  FiBox as Box,
  FiUsers as Users,
  FiMail as Mail,
  FiChevronDown as ChevronDown,
  BiBed as Bed,
  FiScissors as Scissors,
  FiPhone as Phone,
  FiMapPin as MapPin,
  FiFacebook as Facebook,
  FiTwitter as Twitter,
  FiLinkedin as Linkedin,
  FiInstagram as Instagram,
  FaStethoscope as Stethoscope,
  FiActivity as HeartPulse,
  FiPlusSquare as PlusSquare,
  FiArrowRight as ArrowRight,
  FiAward as Award,
  FiClock as Clock,
  FiCheckCircle as CheckCircle,
  FiShield as Shield,
  FiFileText as FileText,
  FiMessageCircle as MessageCircle,
  FiTarget as Target,
  FiEye as Eye,
  FiHeart as Heart,
  BiBuilding as Building,
  FiDownload as Download,
  FiSend as Send,
  FiSettings as Settings,
  FiCheck as Check,
  FiMessageSquare as MessageSquare,
  FiPenTool as PenTool,
  FiSettings as Cog,
  FiHeadphones as Headphones,
  FiArrowLeft as ArrowLeft,
  FaUtensils as Utensils,
  FaWhatsapp,
};
