// Centralized icon exports from lucide-react (modern SVG icons)
import {
  Menu,
  X,
  Home,
  Info,
  Wrench as Tool,
  Package as Box,
  Users,
  Mail,
  ChevronDown,
  Scissors,
  Phone,
  MapPin,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Heart as HeartPulse,
  Plus,
  ArrowRight,
  Award,
  Clock,
  CheckCircle,
  Shield,
  FileText,
  MessageCircle,
  Target,
  Eye,
  Heart,
  Download,
  Send,
  Settings,
  Cog,
  Check,
  MessageSquare,
  Pen as PenTool,
  Headphones,
  ArrowLeft,
  Stethoscope,
  Bed,
  Building,
  Utensils,
} from 'lucide-react';

// Import WhatsApp icon from react-icons/fa as it's specific
import { FaWhatsapp } from 'react-icons/fa';

// Import Font Awesome icons
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faComments, faPencilAlt, faCog, faHeadphones } from '@fortawesome/free-solid-svg-icons';

// Create Font Awesome wrapper components for process icons
const FaCommentsIcon = ({ className }) => <FontAwesomeIcon icon={faComments} className={className} />;
const FaPencilAltIcon = ({ className }) => <FontAwesomeIcon icon={faPencilAlt} className={className} />;
const FaCogIcon = ({ className }) => <FontAwesomeIcon icon={faCog} className={className} />;
const FaHeadphonesIcon = ({ className }) => <FontAwesomeIcon icon={faHeadphones} className={className} />;

export {
  Menu,
  X,
  Home,
  Info,
  Tool,
  Box,
  Users,
  Mail,
  ChevronDown,
  Scissors,
  Phone,
  MapPin,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  HeartPulse,
  Plus as PlusSquare,
  ArrowRight,
  Award,
  Clock,
  CheckCircle,
  Shield,
  FileText,
  MessageCircle,
  Target,
  Eye,
  Heart,
  Download,
  Send,
  Settings,
  Cog,
  Check,
  MessageSquare,
  PenTool,
  Headphones,
  ArrowLeft,
  Stethoscope,
  Bed,
  Building,
  Utensils,
  FaWhatsapp,
  // Font Awesome process icons
  FaCommentsIcon as FaComments,
  FaPencilAltIcon as FaPencilAlt,
  FaCogIcon as FaCog,
  FaHeadphonesIcon as FaHeadphones,
};
